"""Gradient alignment-based test-time adaptation utilities."""

from .grata import (
    GraTa,
    check_model,
    collect_params,
    configure_model,
    copy_model_and_optimizer,
    dynamic_lr_activation,
    gradient_cosine,
    invert_weak_transform,
    load_model_and_optimizer,
    model_logits,
    perturb_parameters,
    restore_parameters,
    soft_target_cross_entropy,
    softmax_entropy,
    strong_style_augmentation,
    transform_weak,
    weak_ensemble_target,
)

__all__ = [
    "GraTa",
    "check_model",
    "collect_params",
    "configure_model",
    "copy_model_and_optimizer",
    "dynamic_lr_activation",
    "gradient_cosine",
    "invert_weak_transform",
    "load_model_and_optimizer",
    "model_logits",
    "perturb_parameters",
    "restore_parameters",
    "soft_target_cross_entropy",
    "softmax_entropy",
    "strong_style_augmentation",
    "transform_weak",
    "weak_ensemble_target",
]
